# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b9a36f85d57f3924c1eababd77f2d6f73eb6558f6485aaefbf9eeded9aff79cdeb37060e4af109c1fecbdafc48f8b238e64987f613901ff1dd6f5654ade6150

test:
  secret_key_base: e41acb7b3ecfc4f23162f5d76e8d7206ab9194835720e5c81138dde5a97d4f0fec2d3bd56c331ac610b67d42297d0e1b63f9668e9ee76680e546366c344c37e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
